language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
install:
  - pip install --user -r requirements.txt
  - pip install .
script:
  pytest -v
after_success:
  codecov
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  server: https://test.pypi.org/legacy/
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "3.6"