language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install .
script: pytest -v
deploy:
  - provider: pypi
    twine_version: 2.0.0
    user: __token__
    password:
      secure: Vqn/di4bSyyRE7ugUeXkw3vzCaUhYF3NpNUq/gYdKJIpmLz0sRWAaBq5uN5BOVBL7ggX9qT0HFxu3H2CQOMEUY8XdZ21nKVM8OyESgZBbqEVk3RncHDyn5w6NgPpjWG/VAIk/bx++4FuHYYHUQ0/mEFYDLctF8HHpKBD5S5fgebnQm0vI9LC6R8Sws5KvcuC0Iy5bPRxCc9hZezJwfRF/dbbZIJDF4aTYxY1To2gfNgt8LE0A56ri/L0/xb/zgki52UYisC2ie1ev0MLKQVy4/sqn31BNudGALV4rOpheWu8fCALEZdoU14VSeQ7Yjn7jMzU/U4HrxtyLdydZMYZVmJZ1+7ee9kSwPfqBcgBdUQPOOLTbcv2ckmJ/Xq5rSM+3MeJ8si3I5bvF1WWG+NduLiqLcqr6a8IciC0sXaQ43Wsd2fE/TfhCrL9v3E8K6nnQcv6EwCOjQBRkCvNF686ScqATO1jkrftW9RlQBF03NvNqmjUAwa6UIygC0O+P8IVT4QK3MkQJ6tT1EhHt9Kzdfx2QEU0jpkAkObxB3WGG4l1kif8o9wbW+TxZonyLagQQPfklNrGEdUm+fowkSgqwo6bjfsAf2q8Ig62O/5vdrHan7Z4xxiNMqRUDzD/eFNN0EdxJfngi0LZnEwR0UJiFXbLMeoTRkRDTnd47yWEpbY=
    distributions: sdist bdist_wheel
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = "3.6"

  - provider: pypi
    user: __token__
    password:
      secure: f02hQ/LeF6K27KPAN3MNweGbvSS2diEvY2pbj95Xd3Jk/p4AdKq+RmKap1oZYSvhojq0VEpjYp7AfHJFrtR2/k+/MRhaRT6kqbChETNH9Y14CgcxsHB/KemOANd/IDmhyc8G5Lfz2XfFlMex2E+ipH3qsCEoUBSrFoPk35Kl+PYu6oTLaTPP2syFH7Im/X5ledFn+4WCxiekTX7uvqxxAXmVMC83cC1qbb2WxECTUpD7ssr1I5Ecxk8CsHuHvdzwK/4WnsE3oBopTQetHJ0Erq+Lsh1LU5ArkLAxeGsZ1CZishiFlxwwd35jNLB3An/0NvWJzQDq01QEOlp2Vr5S407VYv2f1FkDDJilMt4P5JpHCNY7awv8Xevfat/0xfi2Fq+dXlVPt9tH9+sIlnYr5co3aL90nKefz6mc2HwGGERANz9WCDNUq3qeIq82cn9QtpfRedInLAESVunSvSrm2qWlUtP33kfEaf0kyW64v76VCK3C3muBDmhaLq4KJZszUNN0ugNvDh1yQ1d8E/dZAcAxJt2heWExma7m0a3qoG1lhguuX24PLvYsJx0A5o3eL3oe4uPP2ektHEsetL1T+nd2L+YtNLxXi6Gz2K/N7lS3MfnXC1sfsw8LG2FYM4C8xqLHiLvN49ov2Yn46JJU8IrHoj1VF55Pcsx0+HQUiMU=
    distributions: "sdist bdist_wheel"
    server: https://test.pypi.org/legacy/
    on:
      branch: develop
      condition: $TRAVIS_PYTHON_VERSION = "3.6"